class_name ShaderInfo
extends Object

const SHADERS_COMMENT="//SHADERS:"
var name:String
var group:String
var description:String
var author:String
var version:String
var filename:String
var function:String

func loadShaderInfo(shaderInfoJsonObject:Dictionary):
    self.name=shaderInfoJsonObject.name
    self.group=shaderInfoJsonObject.group
    self.description=shaderInfoJsonObject.description
    self.author=shaderInfoJsonObject.author
    self.version=shaderInfoJsonObject.version
    self.filename=shaderInfoJsonObject.filename
    self.function=shaderInfoJsonObject.function

static func readCurrentlyActiveShadersFromShaderCode(selectedShadersCode:String, allShaders:Array[ShaderInfo])->Array[ShaderInfo]:
    var lines:PackedStringArray=selectedShadersCode.split("\n")
    var result:Array[ShaderInfo]=[]
    for line in lines:
        var lineTrimmed=(line as String).trim_prefix(" ")
        if (lineTrimmed.begins_with(SHADERS_COMMENT)):
            var includedShadersName=lineTrimmed.substr(SHADERS_COMMENT.length()).split(",")
            for includedShaderName in includedShadersName:
                var shaderInfo=_searchShaderWithName(includedShaderName,allShaders)
                if(shaderInfo!=null):
                    result.append(shaderInfo)
            return result
    return result


static func _searchShaderWithName(shaderName:String, allShaders:Array[ShaderInfo]) -> ShaderInfo:
    for shader in allShaders:
        if(shader.name.match(shaderName)):
            return shader
    return null

static func generateShaderCode(selectedShaders:Array[ShaderInfo])->String:
    var selectedShadersCode:String=""
    for selectedShader in selectedShaders:
        var contentOfSelectedShader=Util.readFile("res://addons/sprite-shader-mixer/assets/shaders/"+selectedShader.filename)
        selectedShadersCode=selectedShadersCode+"\n"+contentOfSelectedShader
        
    var newShader:Shader=Shader.new()
    newShader.code="""
    //ATTENTION:
    //  THIS IS AN EMPTY SHADED AUTOGENERATED BY
    //  THE ADDON SPRITE-SHADER-MIXER
    //  ANY MANUAL CHANGES WILL BE REMOVED WHEN THE ADDON
    //  UPDATES THIS SHADER.
    //
"""
    newShader.code=newShader.code + SHADERS_COMMENT

    for selectedShader in selectedShaders:
        newShader.code=newShader.code + selectedShader.name + ","

    newShader.code=newShader.code + """
    shader_type canvas_item;
    
        """+selectedShadersCode+"""

    void fragment() {
        vec4 color = texture(TEXTURE, UV);
        vec2 size = vec2(textureSize(TEXTURE, 0));
        vec2 uv = UV;
    
    """
        
    for selectedShader in selectedShaders:
        newShader.code=newShader.code+selectedShader.function+"(uv, TEXTURE, TEXTURE_PIXEL_SIZE, color);\n"
        
    newShader.code=newShader.code + """
        COLOR=color;
    }	
        """
    return selectedShadersCode
